name: Validate the commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install electronic-package-descriptor-by-sporniket
        python -m pip install electronic-symbol-generator-for-cad-by-sporniket
    
    - name: Validate
      run: make all
